name: afacta
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - accelerate=1.8.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.9.1
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.1
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.8
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - datasets=2.14.4
  - dav1d=1.2.1
  - dill=0.3.7
  - expat=2.6.4
  - filelock=3.17.0
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.1.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.31.2
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - jinja2=3.1.6
  - joblib=1.4.2
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kaldi=5.5.1112
  - krb5=1.21.3
  - langchain=0.3.25
  - langchain-text-splitters=0.3.8
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.7
  - libde265=1.0.15
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libheif=1.19.7
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=20.0.0
  - libpng=1.6.49
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libutf8proc=2.10.0
  - libuv=1.51.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.11.2
  - nomkl=1.0
  - numexpr=2.10.1
  - numpy=2.3.0
  - openfst=1.8.3
  - openjpeg=2.5.3
  - openssl=3.5.0
  - optree=0.14.1
  - orc=2.1.2
  - orjson=3.10.14
  - packaging=24.2
  - pandas=2.2.3
  - peft=0.15.2
  - pillow=11.2.1
  - pip=25.1
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.13
  - pytorch=2.7.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.4
  - requests-toolbelt=1.0.0
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlalchemy=2.0.39
  - sqlite=3.50.1
  - svt-av1=3.0.2
  - sympy=1.13.3
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - torchaudio=2.7.1
  - torchvision=0.22.0
  - torchvision-extra-decoders=0.0.2
  - tqdm=4.67.1
  - transformers=4.49.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wheel=0.45.1
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - distro==1.9.0
      - jiter==0.10.0
      - langchain-core==0.3.66
      - langchain-ollama==0.3.3
      - langchain-openai==0.3.24
      - langsmith==0.4.1
      - ollama==0.5.1
      - openai==1.90.0
      - tiktoken==0.9.0
